config/routes.rb
Rails.application.routes.draw do
  resources :sportsplayers , only: [:index, :show, :new, :create, :edit]
  get "sportsplayers/:id/delete", to: "sportsplayers#destroy", as: "destroy" 
  get "delete_all", to: "sportsplayers#delete_all", as: "delete_all"
  # patch "sportsplayer/:id", to: "sportsplayers#show"
  patch "sportsplayers/:id", to: "sportsplayers#update"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sportsplayer.rb
class Sportsplayer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sportsplayers_controller.rb
class SportsplayersController < ApplicationController

    def index
        @sportsplayers = Sportsplayer.all
        render "index"
    end

    def show
        @sportsplayer = Sportsplayer.find(params[:id])
        render "show"
    end

    def new
        @sportsplayer = Sportsplayer.new
        render "new"
    end

    def create
        @sportsplayer = Sportsplayer.find_or_create_by(approved_params(:name, :number, :position, :string, :sport))
        @sportsplayer.save
        redirect_to sportsplayer_path(@sportsplayer)
    end

    def edit
        @sportsplayer = Sportsplayer.find(params[:id])
        render "edit"
    end

    def update
        @sportsplayer = Sportsplayer.find(params[:id])
        @sportsplayer.update(approved_params(:number, :position, :string, :sport))
        redirect_to sportsplayer_path(@sportsplayer)
    end

    def destroy
        Sportsplayer.destroy(params[:id])
        redirect_to sportsplayers_path
    end

    def approved_params(*args)
        params.require(:sportsplayer).permit(*args)
    end

    def delete_all
        Sportsplayer.destroy_all
        redirect_to sportsplayers_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sportsplayers_helper.rb
module SportsplayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Player</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sportsplayers/edit.html.erb
<h1> Edit </h1>

<%= form_for(@sportsplayer) do |f| %>
 
    <%= f.label "Number:" %>
    <%= f.number_field :number%>
    <br>
    <br>
    <%= f.label "Position:" %>
    <%= f.text_field :position %>
    <br>
    <br>
    <%= f.label "String:" %>
    <%= f.text_field :string%>
    <br>
    <br>
    <%= f.label "Sport:" %>
    <!--<%= f.text_field :sport%>-->
    <%= f.select :sport, ["Football", "Baseball", "Basketball", "Hockey", "Golf", "Soccer", "Lacrose", "Swimmming", "Running", "Dodge Ball"] %>
    <br>
    <br>
    <%= f.submit "Edit #{@sportsplayer.name}" %>
    <% end %>

app/views/sportsplayers/index.html.erb
<h1> Index </h1>

<% if !@sportsplayers.empty? %>
    <% @sportsplayers.each do |player| %>
        <p><%= link_to player.name, sportsplayer_path(player) %></p>
    <% end %>
<% else %>
    <p> No players found </p>
<% end %>
    
    
<p><%= button_to "Create new player", new_sportsplayer_path, method: "get" %></p>
<br>
<p><%= button_to "Delete all players", delete_all_path, method: "get", data: {confirm: "Are you sure you want to delete all the players?!"} %></p>

app/views/sportsplayers/new.html.erb
<h1> New Player </h1>

<%= form_for(@sportsplayer) do |f| %>
<%= f.label "Name:" %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label "Number:" %>
<%= f.number_field :number%>
<br>
<br>
<%= f.label "Position:" %>
<%= f.text_field :position %>
<br>
<br>
<%= f.label "String:" %>
<%= f.text_field :string%>
<br>
<br>
<%= f.label "Sport:" %>
<%= f.text_field :sport %>
<br>
<br>
<%= f.submit "Create new player" %>
<% end %>

app/views/sportsplayers/show.html.erb
<h1> <%= @sportsplayer.name %> </h1>

<p> Number: <%= @sportsplayer.number %></p>
<p> Position: <%= @sportsplayer.position %></p>
<p> String: <%= @sportsplayer.string %></p>
<p> Sport: <%= @sportsplayer.sport %></p>
<br>
<p><%= link_to "Back to all players", sportsplayers_path %></p>
<br>
<p><%= link_to "Edit this player", edit_sportsplayer_path(@sportsplayer) %></p>

<br>
<p><%= link_to "Delete this player", destroy_path, data: {confirm: "Are you sure you want to delete #{@sportsplayer.name}?!"} %></p>